# Test configuration for PrepareLonghornDisksStep - Disk with Existing Partitions
# This config tests wiping and formatting a disk that has existing partition table

# Enable only the PrepareLonghornDisksStep
ENABLED_STEPS: "PrepareLonghornDisksStep"

# Disk with existing partitions (no ext4 filesystem)
NO_DISKS_FOR_CLUSTER: false
CLUSTER_DISKS: "/dev/sdd"

# Basic required configuration
FIRST_NODE: true
GPU_NODE: false
CONTROL_PLANE: true

# Domain configuration (required but not used in this step)
DOMAIN: "test.local"
USE_CERT_MANAGER: false

# Cluster configuration
CLUSTER_NAME: "test-cluster"
