#cloud-config
package_update: true
package_upgrade: true

# Install required packages
packages:
  - curl
  - wget
  - jq
  - git

# Load kernel modules
bootcmd:
  - modprobe overlay
  - modprobe br_netfilter

# Ensure kernel modules persist across reboots
write_files:
  - path: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  - path: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1

# Apply sysctl params
runcmd:
  - sysctl --system
  - mkdir -p /opt/cluster-bloom
  - curl -fsSL https://get.jetpack.io/devbox | bash
