#cloud-config
package_update: true
package_upgrade: true

# Install required packages
packages:
  - curl
  - wget
  - jq
  - git
  - htop
  - vim
  - net-tools

# Load kernel modules
bootcmd:
  - modprobe overlay
  - modprobe br_netfilter

# Ensure kernel modules persist across reboots
write_files:
  - path: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  - path: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
  - path: /etc/udev/rules.d/99-fake-disks.rules
    content: |
      # Pretend /dev/sdb is a Samsung SSD
      KERNEL=="sdb", ENV{ID_VENDOR}="ATA", ENV{ID_MODEL}="SamsungSSD"
      # Pretend /dev/sdc is a WDC HDD
      KERNEL=="sdc", ENV{ID_VENDOR}="WDC", ENV{ID_MODEL}="WD10EZEX"

# Apply sysctl params and setup
runcmd:
  - sysctl --system
  - mkdir -p /opt/cluster-bloom
  - curl -fsSL https://get.jetpack.io/devbox | bash

  # Reload udev with the fake attributes
  - udevadm control --reload-rules
  - udevadm trigger
  
  # Partition and format /dev/sdb
  - parted /dev/sdb --script mklabel gpt mkpart primary ext4 0% 100%
  - mkfs.ext4 -F /dev/sdb1
  - mkdir -p /mnt/testdisk1
  - mount /dev/sdb1 /mnt/testdisk1
    
  # Partition and format /dev/sdc
  - parted /dev/sdc --script mklabel gpt mkpart primary ext4 0% 100%
  - mkfs.ext4 -F /dev/sdc1
  - mkdir -p /mnt/testdisk2
   - mount /dev/sdc1 /mnt/testdisk2