# Test configuration for dry-run mode
# This config will only run InstallDependentPackagesStep and fail on chrony

# Enable only the package installation step
ENABLED_STEPS: "InstallDependentPackagesStep"

# Basic required configuration
FIRST_NODE: true
GPU_NODE: false
CONTROL_PLANE: true
NO_DISKS_FOR_CLUSTER: true

# Domain configuration (required but not used in this step)
DOMAIN: "test.local"
USE_CERT_MANAGER: false

# Cluster configuration
CLUSTER_NAME: "test-cluster"
