# Test configuration for PrepareLonghornDisksStep - Already Formatted Disk
# This config tests mounting a disk that already has ext4 filesystem

# Enable only the PrepareLonghornDisksStep
ENABLED_STEPS: "PrepareLonghornDisksStep"

# Disk already formatted with ext4
NO_DISKS_FOR_CLUSTER: false
CLUSTER_DISKS: "/dev/sdc"

# Basic required configuration
FIRST_NODE: true
GPU_NODE: false
CONTROL_PLANE: true

# Domain configuration (required but not used in this step)
DOMAIN: "test.local"
USE_CERT_MANAGER: false

# Cluster configuration
CLUSTER_NAME: "test-cluster"
