# Test configuration for PrepareLonghornDisksStep - Pre-mounted Multiple Disks
# This config will only run PrepareLonghornDisksStep with multiple pre-mounted disks

# Enable only the PrepareLonghornDisksStep
ENABLED_STEPS: "PrepareLonghornDisksStep"

# Pre-mounted disk configuration - multiple disks with spaces
NO_DISKS_FOR_CLUSTER: false
CLUSTER_PREMOUNTED_DISKS: "/mnt/storage1, /mnt/storage2, /mnt/nvme0"

# Basic required configuration
FIRST_NODE: true
GPU_NODE: false
CONTROL_PLANE: true

# Domain configuration (required but not used in this step)
DOMAIN: "test.local"
USE_CERT_MANAGER: false

# Cluster configuration
CLUSTER_NAME: "test-cluster"
