# Test 10: Disk Already in Fstab
# Purpose: Verify error handling when disk UUID already exists in fstab

NO_DISKS_FOR_CLUSTER: false
CLUSTER_DISKS: "/dev/sdb"
CLUSTER_PREMOUNTED_DISKS: ""
ENABLED_STEPS: "PrepareLonghornDisksStep"
FIRST_NODE: true
CONTROL_PLANE: true
CLUSTER_NAME: "test-cluster"
DOMAIN: "test.local"
JOIN_TOKEN: "test-token-12345"
GPU_NODE: false
