# Test 12: Backup Existing Replicas Directory
# Purpose: Verify backup of existing Longhorn replicas directory

NO_DISKS_FOR_CLUSTER: false
CLUSTER_PREMOUNTED_DISKS: "/mnt/storage1"
CLUSTER_DISKS: ""
ENABLED_STEPS: "PrepareLonghornDisksStep"
FIRST_NODE: true
CONTROL_PLANE: true
CLUSTER_NAME: "test-cluster"
DOMAIN: "test.local"
JOIN_TOKEN: "test-token-12345"
GPU_NODE: false
