name: Integration Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Build with devbox
        run: devbox run build

      - name: Run step integration tests
        run: devbox run -- ./dist/bloom test step_integration_tests/*/bloom.yaml
