name: Release Cluster-Bloom

on:
  release:
    types: [created]

jobs:
  buildAndRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Build with devbox
        run: devbox run build -ldflags="-X 'github.com/silogen/cluster-bloom/cmd.Version=$(GITHUB_REF_NAME)'"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
